Blog/config/routes.rb
Rails.application.routes.draw do
  resources :articles do
  resources :comments, only: [:create, :destroy, :update]
  end 
  devise_for :users 
  root 'welcome#index'
end

Blog/app/models/article.rb
class Article < ActiveRecord::Base
	belongs_to :user
	has_many :comments
	validates :title, presence: true, uniqueness: true
	validates :body, presence: true, length: { minimum: 20}
	before_save :set_visits_count

	def update_visits_count
		self.update(visits_count: self.visits_count+1) 
	end

	private 
	def set_visits_count
		self.visits_count ||= 0
	end
end

Blog/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :article
end

Blog/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :articles
  has_many :comments
end

Blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

Blog/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	before_action :authenticate_user!, except: [:index,:show]
	before_action :set_article, except: [:index,:new,:create]
	def index
		@articles=Article.all
	end
	def show
		@article.update_visits_count
		@comment = Comment.new
	end
	def new
		@article= Article.new
	end
	def edit
	end
	def create
		@article = current_user.articles.new(article_params)
		
		if @article.save
			redirect_to @article
		else
			render :new
		end
	end
	def destroy
		@article.destroy
		redirect_to articles_path
	end
	def update
		if @article.update(article_params)
			redirect_to @article
		else
			render :edit
		end
	end	

	private 

	def set_article
		@article=Article.find(params[:id])
	end

	def article_params
		params.require(:article).permit(:title,:body)
	end
end

Blog/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:update, :destroy]
  before_action :set_article
  before_action :authenticate_user! 

  # POST /comments
  # POST /comments.json
  def create
    @comment = current_user.comments.new(comment_params)
    @comment.article = @article
    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment.article, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment.article }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment.article, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to @article, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_article
      @article = Article.find(params[:article_id])
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:user_id, :article_id, :body)
    end
end

Blog/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

Blog/app/helpers/application_helper.rb
module ApplicationHelper
end

Blog/app/helpers/comments_helper.rb
module CommentsHelper
end

Blog/app/helpers/welcome_helper.rb
module WelcomeHelper
end

Blog/app/views/articles/_form.html.erb
<h1><%= name %> articulo</h1>
<%=	form_for(@article) do |f| %>
	<% @article.errors.full_messages.each do |message| %>
		<div>
		* <%= message %>
		</div>
	<% end %>
	<div class="field">
		<%= f.text_field :title, placeholder: "Titulo", class:"form-control" %>
	</div>
	<div class="field">
		<%= f.text_area :body, placeholder: "Escribe aqui el articulo", style:"height:250px;", class:"form-control" %>
	</div>
	<div class="field">
		<%= f.submit "Guardar", class:"btn be-red white" %>
	</div>
<%end%>

Blog/app/views/articles/edit.html.erb
<div style="width:80%;margin:0 auto;">
	<%= render "form", name: "Editar" %>
</div>	

Blog/app/views/articles/index.html.erb
<% @articles.each do |article|%>
<h1><%= link_to article.title, article %></h1>
<div>
	<%= article.body %> - <%= link_to "Eliminar",article, method: :delete %>
</div>
<%end%>

Blog/app/views/articles/new.html.erb
<div style="width:80%;margin:0 auto;">
	<%= render "form", name: "Crear" %>
</div>	

Blog/app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<% unless @article.user.nil? %>
<p>
	Escrito por: <%= @article.user.email %>
</p>
<% end %>
<p>
	Visitas: <%= @article.visits_count %>
</p>
<div>
	<%= @article.body %>
</div>
<div class="field">
	<h3>Comentarios</h3>
	<%= render "comments/form" %>
	<ul id="comments-box">
		<% @article.comments.each do |comment| %>
		<li>
			<%= comment.body %> - <%= comment.user.email %>
		</li>
		<% end %>
	</ul>
</div>
<div>
	<%= link_to "Editar", edit_article_path(@article) %>
</div>

Blog/app/views/comments/_form.html.erb
<%= form_for([@article,@comment], remote: true, html: {id: "comments-form", :"data-type"=>"json"}) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Blog/app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

Blog/app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Article</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.user %></td>
        <td><%= comment.article %></td>
        <td><%= comment.body %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

Blog/app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

Blog/app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @comment.user %>
</p>

<p>
  <strong>Article:</strong>
  <%= @comment.article %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

Blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,700' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render "partials/navigation"%>
	<p class="notice"><%= notice %></p>
	<p class="alert"><%= alert %></p>
	<%= yield %>
</body>
</html>

Blog/app/views/partials/_navigation.html.erb
<header>
	<nav class="be-red white large-padding">
	<ul class="no list row center-xs middle-xs">
		<li class="col-md">
			<h1 class="no-margin" id="logo">Blog del cotiz</h1>
		</li>
		<li class="col-md">
			<%=link_to	"Inicio", root_path %>
		</li>
		<li class="col-md">
			Diseno
		</li>
		<li class="col-md">
			Programacion
		</li>
		<li class="col-md">
			Tecnologia
		</li>
		<% if user_signed_in? %>
		<li class="col-md">
			<%= link_to "Cerrar sesion", destroy_user_session_path, method: :delete %>
		</li>
		<%else%>
		<li class="col-md">
			<%= link_to "Iniciar sesion", new_user_session_path %>
		</li>
		<li class="col-md">
			<%= link_to "Crear cuenta", new_user_registration_path %>
		</li>
		<%end%>
	</ul>
	</nav>
</header>

Blog/app/views/welcome/index.html.erb
<% if user_signed_in?%>
<h1>Bienvenido <%= current_user.email %></h1>
<%else%>
<h1>Bienvenido a esta monda</h1>
<%end%>